version: '3'

services:
  chs-mc-website:
    build: .
    networks:
      - chs-mc-website
    ports:
      - "8080:80"
    environment:
      DB_USER: chs-mc-website
      DB_PASS: 5a7XoNwyRKgDyr9sA2rh
      DB_NAME: mc_stats
      DB_HOST: mariadb

networks:
  chs-mc-website:
    external: true
