version: '3'

services:
  chs-mc-website:
    build: .
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_USER: chs-mc-website
      DB_PASS: hunter2
      DB_NAME: mc_stats
      DB_HOST: mariadb:3306
      MAIL_FROM: hello@example.com
      MAIL_NAME: 'CHS Minecraft Server'
      MAIL_HOST: sandbox.smtp.mailtrap.io
      MAIL_PORT: 2525
      MAIL_USER: whatever
      MAIL_PASS: hunter2
      MAIL_SSL: false
  mariadb:
    image: mariadb:11
    container_name: mariadb
    volumes:
      - mariadb:/var/lib/mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: hunter2
      MYSQL_DATABASE: mc_stats
      MYSQL_USER: chs-mc-website
      MYSQL_PASSWORD: hunter2

volumes:
  mariadb:
