services:
  chs-mc-website:
    build: .
    ports:
      - "3000:3000"
    environment:
      PORT: 3000
      DB_USER: chs-mc-website
      DB_PASS: hunter2
      DB_NAME: mc_stats
      DB_HOST: mariadb
      MAIL_FROM: hello@example.com
      MAIL_NAME: "Your Name"
      MAIL_HOST: smtp-relay.gmail.com
      MAIL_PORT: 465
      MAIL_USER: whatever
      MAIL_PASS: hunter2
      MAIL_SSL: true
    depends_on:
      - mariadb
  mariadb:
    image: mariadb:11
    volumes:
      - mariadb:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: hunter2
      MYSQL_DATABASE: mc_stats
      MYSQL_USER: chs-mc-website
      MYSQL_PASSWORD: hunter2

volumes:
  mariadb:
